print("hii")
print("hello")
print("version 3.0.0")
print("vesion 4.0.0")
print("version 4.1.0")
print("version 4.2.0")
print("version 4.3.0")
print("version 4.4.0")
print("welcome to python programming")
print("python is a great language")
print("python is easy to learn")
print("python is used for web development")
print("version 3.0.0")
